name: Telegram Gate

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types:
      [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: [created]
  push:

jobs:
  build:
    name: Telegram Gate
    runs-on: ubuntu-latest
    steps:
      - name: Notifier
        uses: ethyaan/tgate-action@v1.0.0
        if: always()
        with:
          token: ${{ secrets.token }} # savethe bot token at settings/secrets with name: token
          to: ${{ secrets.to }} # save your chat id at settings/secrets with name: chat
          thread_id: ${{secrets.threadid}} # set this for sending message in thread or group topic
          disable_web_page_preview: false # set this to true to disable link previw in telegram
          disable_notification: false # set tjis true to send message in silet mode
